# Generated by Django 4.0 on 2022-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='total_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderedlist',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
