# Generated by Django 4.0 on 2022-04-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_total_quantity_alter_orderedlist_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderedlist',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
